### ISSUE TITLE
[feature] transition between layouts

### ISSUE THREAD

**Issue by ivalkenburg** [ktquez/vue-extend-layout#1]
First of all thanks for the great package. Exactly what I was looking for. Only thing I am missing is transition between layout,

**Comment by ktquez** [comment]
@uglypony Thank you!

Thanks for this feedback, I will add in the README an example of how to do this with the transition.
When I do, I comment here.

**Comment by llavre** [comment]
@ktquez is there any news? :)

**Comment by sorxrob** [comment]
Would love to get an update too.

**Comment by rainsoft** [comment]
@ktquez is there any news about transition between layout

**Comment by llavre** [comment]
So sad, but seems author didnt support this plugin at all. Already looking for analog.

**Comment by sorxrob** [comment]
@rainsoft @llavre , I am using [this](https://github.com/jaweii/vueg) plugin for my transitions with vue-extend-layout. The good thing with this plugins is that it can automatically determine whether to move forward and backward according to the url depth (/) and history.

**Comment by ktquez** [comment]
@sorxrob 
Thank you for sharing with us.

I think it's perfect to wear together. I will put in the README the option of "visg" plugin for transition effects along with the "vue-extend-layout"
