### ISSUE TITLE
Blank page - layout is not rendered

### ISSUE THREAD

**Issue by dhqvinh** [ktquez/vue-extend-layout#12]
I've tried to use the latest vue-extend-layout version 1.1.1 but it didn't render anything other than a blank page.
After having some times debugging, I found the reason in the index.js:54
```
if (!_options.loader) return
```
With the default config `Vue.use(VueExtendLayout)`, _options.loader is always null, so it doesn't render the layout.

My package.json
```
"dependencies": {
    "vue": "^2.5.16",
    "vue-extend-layout": "^1.1.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  }
```

P/S: version 1.0.1 works just fine.

**Comment by ktquez** [comment]
Thanks @dhqvinh, I'll do some tests

**Comment by ktquez** [comment]
@dhqvinh 
Are you using vue-cli 3?
Are you having any errors on the console?

**Comment by ktquez** [comment]
Fixed:
[v1.1.3](https://github.com/ktquez/vue-extend-layout/tree/v1.1.3)

Additional config for vue-cli 3
https://github.com/ktquez/vue-extend-layout/tree/master#vue-cli-30
