### ISSUE TITLE
Can I use bind properties inside the layout

### ISSUE THREAD

**Issue by stefandevo** [ktquez/vue-extend-layout#19]
Hi
I am struggling with binding a value inside the layout component.
Is this suppose to work or is it just layout?

I have a Auth-layout where I have a `<p>{{ title }}</p>` 
I am trying to set this `title` from the page that is using the layout.

Is this possible?

**Comment by ktquez** [comment]
Can you show us how your layout is?

**Comment by ktquez** [comment]
I didn't understand, is that your question?
https://github.com/ktquez/vue-extend-layout/blob/master/example/src/layouts/page.vue#L4
