### ISSUE TITLE
Not able to change default layouts folder without rewriting path in depency entry point

### ISSUE THREAD

**Issue by llavre** [ktquez/vue-extend-layout#3]
Hello,

What is the right way to set custom path to layouts folder?
Didn't find any information in docs and don't wanna rewrite path in dependency entry point.

**Update:**
 By the way... didn't find any instructions how to start development mode with rollup.
Can you please add it also ? :)

**Comment by ktquez** [comment]
@llavre 
About the layout folder path:
https://github.com/ktquez/vue-extend-layout#create-and-using-layouts

---

So far I only support Webpack, but will soon expand to support Rollup.

**Comment by llavre** [comment]
@ktquez i read whole README.md and your answer, but didn't find answer to my question about how to set custom path for layouts folder (e.g. i wanna make it for my app: **/src/resources/layouts** and not @/layouts).

It's hardcoded inside [layouts.js](https://github.com/ktquez/vue-extend-layout/blob/master/src/layouts.js) at line 7.

Sorry for my broken english.

**Comment by ktquez** [comment]
@llavre 
I understand now.

Actually the path of the `layouts` directory is fixed, it is not possible in this plugin to use dynamic paths as configuration.

**Comment by llavre** [comment]
I think it's not good, in this case here is no way to have custom folder structure.

Maybe you can write some instructions how to start this plugin in development mode? Then I can fork it and make some updates.

Thanks for your patience.

**Comment by llavre** [comment]
@ktquez really will be glad to hear answer about how to start plugin in dev mode to do some fixes.

**Comment by ktquez** [comment]
@llavre 
If you can contribute and submit a pull request would be perfect.

Currently, I can not dedicate myself to my github due to other projects, but I would like to have you or another dev as a developer of this plugin.

**Comment by ggedde** [comment]
I also think this would be a good idea.  I think it would be best as a configuration option when setting Vue.use()

Ex.
```
Vue.use(VueExtendLayout, {
	layoutsDir: '@/app/layouts'
})
```

This is pretty common amongst vue plugins.  Although I haven't written one myself so not sure how hard it would be to add it in :)
